AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Include:
    - 'script/console'
    - 'script/watch'
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false
