AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Include:
    - 'script/console'
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
