services:
  arj_mysql:
    container_name: arj_mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./sql/my.cnf:/etc/mysql/my.cnf:ro
      - ./logs/mysql-general.log:/var/log/mysql-general.log
      - ./logs/mysql-error.log:/var/log/mysql-error.log
    command: mysqld --general-log --general-log-file=/var/log/mysql-general.log --log-error=/var/log/mysql-error.log
    healthcheck:
      test: ['CMD', 'mysql', '--user=root', '--password=root', '--execute', 'show databases;']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
  arj_mysql_healthy:
    container_name: arj_mysql_healthy
    command: 'true'
    image: busybox
    depends_on:
      arj_mysql:
        condition: service_healthy
  arj_postgres:
    container_name: arj_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: arj
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "--host", "localhost", "--username", "root", "--dbname", "arj", "--timeout", "5"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
  arj_postgres_healthy:
    container_name: arj_postgres_healthy
    image: busybox
    depends_on:
      arj_postgres:
        condition: service_healthy
