name: Build, Lint & Test

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**/*.md'
      - '!/todo'
      - '!/.release-notes'
      - '!/scripts/release'
      - '!/scripts/console'
      - '!/LICENSE.txt'
      - '!/.github/dependabot.yml'
      - '!/.github/workflows/release.yml'

jobs:
  build-lint-test-2-7-0-sqlite:
    name: Build, Lint & Test (2.7.0, SQLite)
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
      - name: Lint
        run: make rubocop
      - name: Test
        run: make rspec
  build-lint-test-3-2-2-sqlite:
    name: Build, Lint & Test (3.2.2, SQLite)
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Lint
        run: make rubocop
      - name: Test
        run: make rspec
  test-3-2-2-mysql:
    name: Test (3.2.2, MySQL)
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Test
        run: make rspec-mysql
  test-3-2-2-postgres:
    name: Test (3.2.2, PostgreSQL)
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Test
        run: make rspec-postgres
